### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JuniorzGTX** [TurfuFrogy/EzQR#1]
how do i install it im a noob

i did pip install -r requirements.txt
and after that python main.py but I get this error message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\junio\Downloads\EzQR-main\main.py", line 233, in <module>
    bot.run(botToken)
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 715, in run
    return future.result()
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 694, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 657, in start
    await self.login(token)
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 514, in login
    data = await self.http.static_login(token.strip())
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 410, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002ED2C2769E0>
Traceback (most recent call last):
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\junio\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by TurfuFrogy** [comment]
Hey!
You need to look at the script code and fill all needed variables : whitelistedUsers, botToken and guildIds.

Let me know if it's working after this.
